#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ELEMENT_NOT_FOUND (-1)
#define NOT_FOUND (-1)


#define MAX_COMMAND_LEN 256
#define MAX_DESCRIPTION_LEN 256
#define MAX_LONG_DESCRIPTION_LEN 1024
#define MAX_WANTED_PARAMS 10

#define MAX_RESPONSES 5
#define MAX_RESPONSE_ROWS 10
#define MAX_RESPONSE_ROW_LENGTH 1024

#define MAX_STRING_ARRAY_ELEMENTS 10

#define BUFFER_SIZE 1024

#endif //CONSTANTS_H
