"""
Display Product Identification Information
"""
ATI = 'ATI'
AT_READ_IMEI = 'AT+CGSN=1'  # <snt>
AT_READ_POWER_SUPPLY_VOLTAGE = 'AT+CBC'

"""
Basic Setup
"""
AT_WRITE_FULL_PHONE_FUNCTIONALITY = 'AT+CFUN=1'
AT_WRITE_OLD_SCRAMBLING_ALGORITHM = 'AT+QSPCHSC=1'
AT_WRITE_EPS_STATUS_CODES = 'AT+CEREG=5'
AT_WRITE_TURN_OFF_PSM = 'AT+CPSMS=0'
AT_WRITE_CONNECTION_STATUS_URC = 'AT+CSCON=1'
# AT_READ_CONNECTION_STATUS = 'AT+CSCON?'
AT_WRITE_ENABLE_WAKEUP_INDICATION = 'AT+QATWAKEUP=1'
AT_READ_IS_WAKEUP_INDICATION_ENABLED = 'AT+QATWAKEUP?'
# AT_RESET_MODULE = 'AT+QRESET=1'# Reset here? Check if there is any variable that does not take effect immediately


"""
SETUP OF CONNECTION 
"""
AT_WRITE_OPERATOR_SELECTION = 'AT+COPS=1,2,"21901"'
AT_EXECUTE_EXTENDED_SIGNAL_QUALITY = "AT+CESQ"
AT_READ_CONNECTION_STATUS = "AT+CSCON?"
AT_READ_OPERATOR_SELECTION = 'AT+COPS?'
AT_WRITE_ATTACH_TO_PACKET_DOMAIN_SERVICE = 'AT+CGATT=1'

AT_READ_PDP_CONTEXT_STATE = 'AT+CGACT?'
AT_WRITE_PDP_CONTEXT_STATUS_DEACTIVATE = 'AT+CGACT=0,1'
AT_WRITE_ACTIVATE_PDN_CTX = 'AT+QGACT=1,1,"iot.ht.hr"'

AT_TEST_EXTENDED_SIGNAL_QUALITY = 'AT+CESQ=?'
AT_READ_EPS_NETWORK_REGISTRATION_STATUS = 'AT+CEREG?'  # +CEREG: 0,1
AT_READ_PDP_CONTEXTS = 'AT+CGDCONT?'  # Read pdp context info. RESPONSE: +CGDCONT: 1,"IP","iot.ht.hr","10.157.140.5",0,0,0,,,,,,0,,0
AT_READ_SHOW_PDP_ADDRESS = 'AT+CGPADDR?'  # Read the Ip address. RESPONSE: +CGPADDR: 1,10.157.140.5
AT_READ_UE_IP_ADDRESS = 'AT+QIPADDR'  # Read Ip of a DEVICE +QIPADDR: 10.152.26.119 +QIPADDR: 127.0.0.1
# TCP/IP
# 188.252.207.207 KOMP
# 20.234.113.19 AZURE
#AT_WRITE_OPEN_SOCKET_SERVICE = 'AT+QIOPEN=1,0,"UDP","20.234.113.19",4445,4445,1,0'  # contextID = 1, connectionid = 0, DIRECT PUSH MODE = 1
# AT+QISEND=0,5,12345
# AT+QISENDEX=0,5,3132333435
AT_CLOSE_SOCKET = 'AT+QICLOSE=0'
AT_READ_SOCKET_STATE = 'AT+QISTATE=1,0'  # Query the connection status of socket service 0.
# AT+QISEND=,0          #queries whether the data has reached the server.
AT_GET_LAST_ERROR_DESCRIPTION = 'AT+QIGETERROR'
AT_BASIC_INFO_SEQUENCE = [ATI, AT_READ_OPERATOR_SELECTION, AT_READ_PDP_CONTEXTS, AT_READ_SHOW_PDP_ADDRESS]
